---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:6.7.7-community
          ports:
          - name: http-port
            containerPort: 9000
      hostNetwork: true
      dnsPolicy: ClusterFirst
  #   volumeMounts:
  #     - name: sonar-conf
  #       mountPath: /opt/sonarqube/conf
  #     - name: sonar-data
  #       mountPath: /opt/sonarqube/data
  #     - name: sonar-logs
  #       mountPath: /opt/sonarqube/logs
  #     - name: sonar-extensions
  #       mountPath: /opt/sonarqube/extensions
  # volumes:
  #   - name: sonar-conf
  #     hostPath:
  #       path: /opt/sonarqube/conf
  #   - name: sonar-data
  #     hostPath:
  #       path: /opt/sonarqube/data
  #   - name: sonar-logs
  #     hostPath:
  #       path: /opt/sonarqube/logs
  #   - name: sonar-extensions
  #     hostPath:
  #       path: /opt/sonarqube/extensions
