apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  labels:
    k8s-app: sonarqube
    app: sonarqube
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
  - name: web
    nodePort: 31020
    protocol: TCP
    port: 9000
    targetPort: 9000
