apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    k8s-app: jenkins
    app: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - name: http
    nodePort: 31010
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: web
    nodePort: 31011
    protocol: TCP
    port: 50000
    targetPort: 50000
