apiVersion: v1
kind: Service
metadata:
  name: test-app
  labels:
    k8s-app: test-app
    app: test-app
spec:
  type: NodePort
  selector:
    app: test-app
  ports:
  - name: web
    nodePort: 31050
    protocol: TCP
    port: 80
    targetPort: 8050
